/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import Entidades.Servicio;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Proyecto
 */
public class FormGestionEmpleados extends javax.swing.JFrame {

    Menu menu;
    ArrayList<Servicio> servicios;
    ArrayList<String> especialidades;
    EmpleadosTableModel em = new EmpleadosTableModel();
    String oldNum, oldNom, oldApe, oldDir, oldTel;
  
    /**
     * Creates new form FormGestionEmpleados
     */
    public FormGestionEmpleados() throws ClassNotFoundException, SQLException {
        initComponents();
        servicios = new ArrayList<Servicio>();
        cbEnfSer.removeAllItems();
        cbEnfSer.addItem("Seleccione un servicio");
        cbEspecialidad.removeAllItems();
        cbEspecialidad.addItem("Seleccione una especialidad");
        cargarComboBox();
        btnFEli.setEnabled(false);
        btnFMod.setEnabled(false);
    }
    
    private void cargarComboBox() throws ClassNotFoundException, SQLException{
        //Servicios
        Conexion conn = new Conexion();
        servicios = conn.getServicios();
        
        for(Servicio serv: servicios){
            cbEnfSer.addItem(serv.getCodigo());
        }
        
        //Especialidades
        especialidades = conn.getEspecialidades();
        
        for(String esp: especialidades){
            cbEspecialidad.addItem(esp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        rbMedico = new javax.swing.JRadioButton();
        rbEnfermera = new javax.swing.JRadioButton();
        rbDirector = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        panelMed = new javax.swing.JPanel();
        lbMedEsp = new javax.swing.JLabel();
        cbEspecialidad = new javax.swing.JComboBox<>();
        panelEnf = new javax.swing.JPanel();
        lbEnfSer = new javax.swing.JLabel();
        lbEnfTur = new javax.swing.JLabel();
        lbEnfSal = new javax.swing.JLabel();
        txtEnfSalario = new javax.swing.JTextField();
        cbEnfTur = new javax.swing.JComboBox<>();
        cbEnfSer = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tEmpleados = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        rbFDoc = new javax.swing.JRadioButton();
        rbFEnf = new javax.swing.JRadioButton();
        btnFMod = new javax.swing.JButton();
        btnFEli = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFNum = new javax.swing.JTextField();
        txtFNom = new javax.swing.JTextField();
        btnFBus = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMDir = new javax.swing.JTextField();
        txtMNom = new javax.swing.JTextField();
        txtMAp = new javax.swing.JTextField();
        txtMTel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnTEmp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(970, 550));

        jLabel1.setText("Número");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Teléfono");

        jLabel5.setText("Dirección");

        rbMedico.setSelected(true);
        rbMedico.setText("Médico");
        rbMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMedicoActionPerformed(evt);
            }
        });

        rbEnfermera.setText("Enfermera");
        rbEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEnfermeraActionPerformed(evt);
            }
        });

        rbDirector.setText("Director");
        rbDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDirectorActionPerformed(evt);
            }
        });

        jLabel6.setText("Rol:");

        lbMedEsp.setText("Especialidad");

        cbEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspecialidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMedLayout = new javax.swing.GroupLayout(panelMed);
        panelMed.setLayout(panelMedLayout);
        panelMedLayout.setHorizontalGroup(
            panelMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMedEsp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbEspecialidad, 0, 107, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMedLayout.setVerticalGroup(
            panelMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMedEsp)
                    .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        lbEnfSer.setText("Servicio");

        lbEnfTur.setText("Turno");

        lbEnfSal.setText("Salario");

        txtEnfSalario.setEnabled(false);
        txtEnfSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnfSalarioActionPerformed(evt);
            }
        });

        cbEnfTur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JOUR", "NUIT" }));
        cbEnfTur.setEnabled(false);

        cbEnfSer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEnfSer.setEnabled(false);
        cbEnfSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnfSerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEnfLayout = new javax.swing.GroupLayout(panelEnf);
        panelEnf.setLayout(panelEnfLayout);
        panelEnfLayout.setHorizontalGroup(
            panelEnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnfLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelEnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEnfSer)
                    .addComponent(lbEnfTur)
                    .addComponent(lbEnfSal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbEnfTur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEnfSer, 0, 99, Short.MAX_VALUE)
                    .addComponent(txtEnfSalario, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        panelEnfLayout.setVerticalGroup(
            panelEnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnfLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelEnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnfSer)
                    .addComponent(cbEnfSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEnfTur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEnfTur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnfSal)
                    .addComponent(txtEnfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(13, 13, 13)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbMedico)
                            .addComponent(txtTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txNum, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)))
                    .addComponent(panelMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtAp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbEnfermera))
                        .addGap(115, 115, 115)
                        .addComponent(rbDirector))
                    .addComponent(panelEnf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(359, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(410, 410, 410))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDirector)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbMedico)
                        .addComponent(jLabel6))
                    .addComponent(rbEnfermera, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar empleado", jPanel2);

        tEmpleados.setModel(em);
        tEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tEmpleados);

        jLabel7.setText("Filtro por");

        rbFDoc.setSelected(true);
        rbFDoc.setText("Doctor");
        rbFDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFDocActionPerformed(evt);
            }
        });

        rbFEnf.setText("Enfermero");
        rbFEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFEnfActionPerformed(evt);
            }
        });

        btnFMod.setText("Modificar");
        btnFMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFModActionPerformed(evt);
            }
        });

        btnFEli.setText("Eliminar");
        btnFEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFEliActionPerformed(evt);
            }
        });

        jLabel8.setText("Número");

        jLabel9.setText("Nombre");

        btnFBus.setText("Buscar");
        btnFBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFBusActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombre");

        jLabel11.setText("Dirección");

        jLabel12.setText("Teléfono");

        jLabel13.setText("Apellido");

        jLabel14.setText("Actualización");

        btnTEmp.setText("Todos Empleados");
        btnTEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnFMod, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnFEli, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMNom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMTel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel14)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFNom, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFNum, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rbFDoc)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbFEnf)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMDir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtMAp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnTEmp))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFBus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(rbFDoc)
                                    .addComponent(rbFEnf))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtFNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtFNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(jLabel14))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(btnFBus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtMNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtMAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtMTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFMod, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFEli, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Lista de empleados", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 797, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDirectorActionPerformed
        // TODO add your handling code here:
        rbMedico.setSelected(false);
        rbEnfermera.setSelected(false);
        cbEnfSer.setEnabled(false);
        cbEnfTur.setEnabled(false);
    }//GEN-LAST:event_rbDirectorActionPerformed

    private void rbEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEnfermeraActionPerformed
        // TODO add your handling code here:
        rbMedico.setSelected(false);
        rbDirector.setSelected(false);
        cbEspecialidad.setEnabled(false);
        cbEnfSer.setEnabled(true);
        cbEnfTur.setEnabled(true);
        txtEnfSalario.setEnabled(true);
    }//GEN-LAST:event_rbEnfermeraActionPerformed

    private void txtEnfSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnfSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnfSalarioActionPerformed

    private void rbMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMedicoActionPerformed
        // TODO add your handling code here:
        rbEnfermera.setSelected(false);
        rbDirector.setSelected(false);
        cbEnfSer.setEnabled(false);
        cbEnfTur.setEnabled(false);
        cbEspecialidad.setEnabled(true);
    }//GEN-LAST:event_rbMedicoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cbEnfSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnfSerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEnfSerActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String num = txNum.getText();
        String nom = txtAp.getText();
        String prenom = txtNom.getText();
        String adresse = txtDir.getText();
        String tel = txtTel.getText();
        boolean valido = true;
        boolean error = false;
        boolean vacio = false;

        if("".equals(num) && "".equals(nom) && "".equals(prenom) && "".equals(adresse) && "".equals(tel)){
             JOptionPane.showMessageDialog(
                      this,
                      "Debe ingresar datos a todos los campos",
                      "Registro empleados",
                      JOptionPane.ERROR_MESSAGE);
             valido = false;
             vacio = true;
        }
        else{
             if(!error){
                 try{
                     int n = Integer.parseInt(num);
                      }catch(NumberFormatException nfe){
                         JOptionPane.showMessageDialog(
                               this,
                               "Solo se debe ingresar numeros en el campo numero",
                               "Registro empleados",
                               JOptionPane.ERROR_MESSAGE);
                         valido = false;
                         error = true;
                         txNum.setText("");
                      }
             }
             else if(!error){
                 try{
                int n = Integer.parseInt(tel);
                 }catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(
                          this,
                          "Solo se debe ingresar numeros en el campo telefono",
                          "Registro empleados",
                          JOptionPane.ERROR_MESSAGE);
                    valido = false;
                    error = true;
                    txNum.setText("");
                 } 
             }  
             else if(!error){
                  try{
                     int n = Integer.parseInt(prenom);
                     JOptionPane.showMessageDialog(
                           this,
                           "Solo se debe ingresar letras en el campo nombre",
                           "Registro empleados",
                           JOptionPane.ERROR_MESSAGE);
                     valido = false;
                     error = true;
                     txNum.setText("");
                  }catch(NumberFormatException nfe){
                      if(!"".equals(prenom))
                         valido = true;               
                  }
             } 
             if(!error){
                  try{
                     int n = Integer.parseInt(nom);
                     JOptionPane.showMessageDialog(
                           this,
                           "Solo se debe ingresar letras en el campo apellido",
                           "Registro empleados",
                           JOptionPane.ERROR_MESSAGE);
                     valido = false;
                     error = true;
                     txNum.setText("");
                  }catch(NumberFormatException nfe){
                      if(!"".equals(nom))
                         valido = true;               
                  } 
             }
             else if(!error){
                 if("".equals(adresse)){
                  JOptionPane.showMessageDialog(
                      this,
                      "Debe ingresar valores en el campo dirección",
                      "Registro empleados",
                      JOptionPane.ERROR_MESSAGE);
                valido = false;
                error = true;
             }
             }
        }
        if(!vacio && rbMedico.isSelected()){
            if(cbEspecialidad.getSelectedItem().toString().equals("Seleccione una especialidad")){
            JOptionPane.showMessageDialog(
                      this,
                      "Seleccione una especialidad",
                      "Registro empleados",
                      JOptionPane.ERROR_MESSAGE);
                valido = false;
                error = true;                 
             }
             else{
                 if(!error)
                     valido = true;
             }
        }
        else if(!vacio && rbEnfermera.isSelected()){
            if(cbEnfSer.getSelectedItem().toString().equals("Seleccione un servicio")){
            JOptionPane.showMessageDialog(
                      this,
                      "Seleccione un servicio",
                      "Registro empleados",
                      JOptionPane.ERROR_MESSAGE);
                valido = false;
                error = true;                 
             }
             else{
                 if(!error)
                     valido = true;
             }
            try{
                 int n = Integer.parseInt(txtEnfSalario.getText());
             }catch(NumberFormatException nfe){
                 JOptionPane.showMessageDialog(
                      this,         
                      "Solo se debe ingresar numeros en el campo salario",         
                      "Registro empleados",         
                 JOptionPane.ERROR_MESSAGE);                      
                     valido = false;
                     error = true;
                     txNum.setText("");
             }             
             if(!error)
                valido = true;
        }

         if(valido){
             try {
             // TODO add your handling code here:
             new Conexion().ejecutarQuery("insert into employe(numero, nom, prenom, adresse, tel) "
                     + "values("+num+", '"+nom+"', '"+prenom+"', '"+adresse+"', '"+tel+"')");
         } catch (ClassNotFoundException | SQLException ex) {
             //ex.printStackTrace();
             JOptionPane.showMessageDialog(
                      this,         
                      "Numero dupliacado",         
                      "Registro empleados",         
                 JOptionPane.ERROR_MESSAGE);                      
                     valido = false;
                     error = true;
         }

         if(rbMedico.isSelected()){
             String esp = cbEspecialidad.getSelectedItem().toString();
             try {
             // TODO add your handling code here:
             new Conexion().ejecutarQuery("insert into docteur(numero, specialite) "
                     + "values("+num+", '"+esp+"')");
             } catch (ClassNotFoundException | SQLException ex) {
                 //ex.printStackTrace();
             }
         }
         else if(rbEnfermera.isSelected()){
             String serv = cbEnfSer.getSelectedItem().toString();
             String tur = cbEnfTur.getSelectedItem().toString();
             int sal = Integer.parseInt(txtEnfSalario.getText());
             try {
             // TODO add your handling code here:
             new Conexion().ejecutarQuery("insert into infirmier(numero, code_service,rotation,salaire) "
                     + "values("+num+", '"+serv+"', '"+tur+"', "+sal+")");
             } catch (ClassNotFoundException | SQLException ex) {
                 //ex.printStackTrace();
             }
         }
     }
        txNum.setText("");
        txtNom.setText("");
        txtAp.setText("");
        txtDir.setText("");
        txtTel.setText("");
        txtEnfSalario.setText("");
        cbEnfSer.setSelectedIndex(0);
        cbEspecialidad.setSelectedIndex(0);
        em = new EmpleadosTableModel();
        tEmpleados.setModel(em);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void rbFDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFDocActionPerformed
        // TODO add your handling code here:
        rbFEnf.setSelected(false);
    }//GEN-LAST:event_rbFDocActionPerformed

    private void rbFEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFEnfActionPerformed
        // TODO add your handling code here:
        rbFDoc.setSelected(false);
    }//GEN-LAST:event_rbFEnfActionPerformed

    private void btnFBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFBusActionPerformed
        // TODO add your handling code here:
        boolean valido = true;
        boolean error = false;
        int n = 0;
        
        if(rbFDoc.isSelected() || rbFEnf.isSelected()){
            if(!txtFNum.getText().equals("")){
              try{
                n = Integer.parseInt(txtFNum.getText());
                 }catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(
                          this,
                          "Solo se debe ingresar numeros en el campo número",
                          "Lista de empleados",
                          JOptionPane.ERROR_MESSAGE);
                    txNum.setText("");
                    valido = false;
                 } 
            }
            if(!txtFNom.getText().equals("")){
                 try{
                   n = Integer.parseInt(txtFNum.getText());
                    JOptionPane.showMessageDialog(
                             this,
                             "Solo se debe ingresar letras en el campo nombre",
                             "Lista de empleados",
                             JOptionPane.ERROR_MESSAGE);
                       txNum.setText("");
                       valido = false;
                    }catch(NumberFormatException nfe){

                    } 
           }
           if(valido){
               if(rbFDoc.isSelected()){
               if(n == 0 && "".equals(txtFNom.getText()))
                  em = new EmpleadosTableModel("Doctor",0,"");
               else if(n!=0){
                   em = new EmpleadosTableModel("Doctor", Integer.parseInt(txtFNum.getText()),"");
               }
               else if(!"".equals(txtFNom.getText())){
                   em = new EmpleadosTableModel("Doctor", 0,txtFNom.getText());
               }
           }
           else if(rbFEnf.isSelected()){
               if(n == 0 && "".equals(txtFNom.getText()))
                  em = new EmpleadosTableModel("Enfermero", 0,"");
               else if(n!=0){
                   em = new EmpleadosTableModel("Enfermero", Integer.parseInt(txtFNum.getText()),"");
               }
               else if(!"".equals(txtFNom.getText())){
                   em = new EmpleadosTableModel("Enfermero", 0,txtFNom.getText());
               }
           }
           else{
               if(n == 0 && "".equals(txtFNom.getText()))
                  em = new EmpleadosTableModel("Empleado", 0,"");
               else if(n!=0){
                   em = new EmpleadosTableModel("Empleado", Integer.parseInt(txtFNum.getText()),"");
               }
               else if(!"".equals(txtFNom.getText())){
                   em = new EmpleadosTableModel("Empleado", 0,txtFNom.getText());
               }
        }
        }
        tEmpleados.setModel(em);
        }
        else{
            JOptionPane.showMessageDialog(
                      this,         
                      "Ningun dato seleccionado",         
                      "Error",         
                 JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnFBusActionPerformed

    private void btnFModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFModActionPerformed
        // TODO add your handling code here:h
       String num = oldNum;
       String nom = txtMAp.getText();
       String prenom = txtMNom.getText();
       String adresse = txtMDir.getText();
       String tel = txtMTel.getText();

        String cmd = String.format("update employe set numero=%s, nom='%s', prenom='%s', adresse='%s', tel='%s' where numero=%s and nom='%s' and prenom='%s' and adresse='%s' and tel='%s'", num, nom, prenom, adresse, tel, oldNum, oldApe, oldNom, oldDir, oldTel);
        try {
            if (JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de modificar este registro?",
                "Modificar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            new Conexion().ejecutarQuery(cmd);
            limpiar();
        }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
        
        if(rbFDoc.isSelected())
           em = new EmpleadosTableModel("","","","");
        else if(rbFEnf.isSelected())
           em = new EmpleadosTableModel("Enfermero", 0,"");
        else
            em = new EmpleadosTableModel();
        
        tEmpleados.setModel(em);
        
        btnFEli.setEnabled(false);
        btnFMod.setEnabled(false);
    }//GEN-LAST:event_btnFModActionPerformed

    private void tEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEmpleadosMouseClicked
        // TODO add your handling code here:
          if(evt.getClickCount()==2){
            oldNum = (""+tEmpleados.getValueAt(tEmpleados.getSelectedRow(), 0));
            txtMNom.setText(""+tEmpleados.getValueAt(tEmpleados.getSelectedRow(), 1));
            txtMAp.setText(""+tEmpleados.getValueAt(tEmpleados.getSelectedRow(), 2));
            txtMDir.setText(""+tEmpleados.getValueAt(tEmpleados.getSelectedRow(), 3));
            txtMTel.setText(""+tEmpleados.getValueAt(tEmpleados.getSelectedRow(), 4));
           
            btnFEli.setEnabled(true);
            btnFMod.setEnabled(true);
        }
        oldApe = txtMAp.getText();
        oldNom = txtMNom.getText();
        oldDir = txtMDir.getText();
        oldTel = txtMTel.getText();
    }//GEN-LAST:event_tEmpleadosMouseClicked

    private void btnFEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFEliActionPerformed
        // TODO add your handling code here:
       String nom = txtMAp.getText();
       String prenom = txtMNom.getText();
       String adresse = txtMDir.getText();
       String tel = txtMTel.getText();

       String cmd2 = "";
       String cmd3 = "";
       
        if(rbFDoc.isSelected()){
            cmd2 = String.format("delete from docteur where  numero=%s",oldNum);
           try {
               if (JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar este registro?",
                "Eliminar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                 new Conexion().ejecutarQuery(cmd2);
            
                 limpiar();
                }
            } catch (ClassNotFoundException | SQLException ex) {
               Logger.getLogger(FormGestionEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(rbFEnf.isSelected())
        {
            cmd3 = String.format("delete from infirmier where  numero=%s",oldNum);
            try {
            if (JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar este registro?",
                "Eliminar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                new Conexion().ejecutarQuery(cmd3);
            
                limpiar();
            }
            } catch (ClassNotFoundException | SQLException ex) {
                ex.printStackTrace();
            }

        }
        else{
            String cmd1 = String.format(
            "delete from employe where numero =%s and nom='%s' and prenom='%s' and adresse='%s' and tel='%s'",
             oldNum, nom, prenom, adresse, tel);
            try {
            if (JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar este registro?",
                "Eliminar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                new Conexion().ejecutarQuery(cmd1);
            
                limpiar();
            }
            } catch (ClassNotFoundException | SQLException ex) {
                ex.printStackTrace();
            } 
        }        
        if(rbFDoc.isSelected())
           em = new EmpleadosTableModel("","","","");
        else if(rbFEnf.isSelected())
            em = new EmpleadosTableModel("Enfermero", 0,"");
        else
            em = new EmpleadosTableModel();
        tEmpleados.setModel(em);
        
        btnFEli.setEnabled(false);
        btnFMod.setEnabled(false);
    }//GEN-LAST:event_btnFEliActionPerformed

    private void cbEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEspecialidadActionPerformed

    private void btnTEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTEmpActionPerformed
        // TODO add your handling code here:
        em = new EmpleadosTableModel();
        tEmpleados.setModel(em);
        rbFDoc.setSelected(false);
        rbFEnf.setSelected(false);
        limpiar();
    }//GEN-LAST:event_btnTEmpActionPerformed

     private void limpiar(){
        txtMAp.setText("");
        txtMNom.setText("");
        txtMDir.setText("");
        txtMTel.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormGestionEmpleados().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FormGestionEmpleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FormGestionEmpleados.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFBus;
    private javax.swing.JButton btnFEli;
    private javax.swing.JButton btnFMod;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnTEmp;
    private javax.swing.JComboBox<String> cbEnfSer;
    private javax.swing.JComboBox<String> cbEnfTur;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbEnfSal;
    private javax.swing.JLabel lbEnfSer;
    private javax.swing.JLabel lbEnfTur;
    private javax.swing.JLabel lbMedEsp;
    private javax.swing.JPanel panelEnf;
    private javax.swing.JPanel panelMed;
    private javax.swing.JRadioButton rbDirector;
    private javax.swing.JRadioButton rbEnfermera;
    private javax.swing.JRadioButton rbFDoc;
    private javax.swing.JRadioButton rbFEnf;
    private javax.swing.JRadioButton rbMedico;
    private javax.swing.JTable tEmpleados;
    private javax.swing.JTextField txNum;
    private javax.swing.JTextField txtAp;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtEnfSalario;
    private javax.swing.JTextField txtFNom;
    private javax.swing.JTextField txtFNum;
    private javax.swing.JTextField txtMAp;
    private javax.swing.JTextField txtMDir;
    private javax.swing.JTextField txtMNom;
    private javax.swing.JTextField txtMTel;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
